### Prueba

GET http://localhost:5000/api/autores/test

### Nuevo Autor

POST http://localhost:5000/api/autores/nuevo
Content-Type: application/json

{
    "nombreAutores":"Gabriel Garcia Marquez"
}

### Todos los Autores

GET http://localhost:5000/api/autores

### Autor por ID

GET http://localhost:5000/api/autores/6128027792d513317573956d

### Editar Autor por Id

PUT http://localhost:5000/api/autores/6128022192d5133175739568
Content-Type: application/json

{
    "nombreAutores": "Gabriel Garcia Marquez editado"
   
}


### Eliminar Autor por ID

DELETE http://localhost:5000/api/autores/6128022192d5133175739568